# Generated by Django 5.0 on 2024-01-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='no_of_product',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
