# Generated by Django 5.0 on 2024-05-01 03:23

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=product.models.generate_order_id, max_length=18),
        ),
    ]
