# Generated by Django 5.0 on 2024-05-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
