# Generated by Django 5.0 on 2023-12-25 03:31

import django.db.models.deletion
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email_id_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=user.models.get_token, max_length=128)),
                ('user_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
