# Generated by Django 5.0 on 2023-12-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useractivationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivationtoken',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
